include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

  errors:
    invalid_annotation_target: ignore

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Errors
    avoid_empty_else: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true

    # Style
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_constructors_first: true

    # Pub
    sort_pub_dependencies: true
