#!/bin/bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

flutter clean
rm -rf build

# iOS — CocoaPods (unlike ../tribly/mobile, which moved to Swift Packages; the Podfile's
# post_install sets the PERMISSION_* macros permission_handler needs, so Pods stay).
rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/Flutter/ephemeral

# Android — .kotlin is generated by AGP's built-in Kotlin (android.builtInKotlin=true).
rm -rf android/.gradle android/.kotlin android/app/build android/build
cd android && ./gradlew clean 2>/dev/null || true && cd ..

# Reinstall
flutter pub get
cd ios && pod install --repo-update && cd ..

# Regenerate freezed/riverpod/json sources — without this a `flutter analyze` straight after
# a clean fails on the missing .g.dart / .freezed.dart parts.
dart run build_runner build --delete-conflicting-outputs
